- generators/app/index.js
This is a possible fix to https://github.com/github/hubot/issues/838 . Currently, if you say `yo hubot --adapter slack`, the adapter ends up being set to `true`.
This PR specifies a type for each option to String or Boolean. It doesn't seem to quite prevent the bad behavior yet, so needs some work:
```
2.1.4-github ~/src/scratchbot 
$ yo hubot --adapter
_____________________________
/                             \
//\              |      Extracting input for    |
////\    _____    |   self-replication process   |
//////\  /_____\   \                             /
======= |[^_/\_]|   /----------------------------
|   | _|___@@__|__
+===+/  ///     \_\
| |_\ /// HUBOT/\\
|___/\//      /  \\
\      /   +---+
\____/    |   |
| //|    +===+
\//      |xx|
? Owner: Josh Nichols …
```
> Fix option parsing to prevent trying to install `hubot-true`

- generators/script/templates/_package.json
While reviewing https://github.com/github/generator-hubot/pull/6, I realized that `grunt test` doesn't work because coffeescript is missing :sweat: 
This adds the same version of coffee-script that hubot upstream is currently using.
> Add coffee-script as a development dependency

- generators/script/templates/_package.json
Latest version of `sinon-chai` has `peerDependencies` for `sinon` and `chai`, that the explicit unbounded dependency here conflicts with. Specifically `sinon-chai` wants a version of `chai` < 2 however the latest version is > 2 and ends up conflicting.
The error encountered was during the final step of `yo hubot:script` (the npm install part):
```
npm ERR! Linux 3.2.0-75-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code EPEERINVALID
npm ERR! peerinvalid The package chai does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer sinon-chai@2.6.0 wants chai@>=1.9.2 <2
```
> Let sinon-chai deal with sinon and chai

- generators/app/index.js
This was reported in https://github.com/github/generator-hubot/issues/15 . For some reason, `this.user.git.name` and `this.user.git.email` in this case weren't functions.
This is a workaround to check their type before calling them. If they aren't functions, they are assumed to be the value.
> Only call git helper functions if they are functions

- generators/app/templates/Procfile
- generators/app/templates/bin/hubot
- generators/app/templates/bin/hubot.cmd
It feels weird to name the bot during setup and then have it called `Hubot` regardless in local testing. So lets not do that anymore :smile_cat:
> Use hubot's name in shell adapter

- generators/script/templates/.travis.yml
- generators/script/templates/Gruntfile.js
- generators/script/templates/_package.json
- generators/script/templates/gitignore
- Update dependencies
- Add missing grunt and grunt-cli packages
- Re-add chai and sinon to be npm 3.x compliant
- Lock coffee-script to the same as hubot
- Update travis config
- Use new container architecture
- Cache node_modules (faster test runs)
- Switch from node 0.11 to 0.12 for testing
- Add iojs to test matrix
- Update Gruntfile
- Add src directory to watch list
- Load additional grunt tasks in consistent manor
- Remove superfluous watch log message
> Update script generator to work OOTB

- CHANGELOG.md
- generators/app/templates/scripts/example.coffee
* [app] update example.coffee to use `res` instead of `msg` - cc @geoffreyanderson  https://github.com/github/generator-hubot/pull/36
* [script] update generator to work better out of the box cc @mal https://github.com/github/generator-hubot/pull/34
- Update dependencies
- Add missing grunt and grunt-cli packages
- Re-add chai and sinon to be npm 3.x compliant
- Lock coffee-script to the same as hubot
- Update travis config
- Use new container architecture
- Cache node_modules (faster test runs)
- Switch from node 0.11 to 0.12 for testing
- Add iojs to test matrix
- Update Gruntfile
- Add src directory to watch list
- Load additional grunt tasks in consistent manor
- Remove superfluous watch log message
> Release 0.3.0

- generators/app/index.js
Context: user puts in an adapter that doesn't exist.
Current:
```
? Description: A simple helpful robot for your Company
? Bot adapter: (campfire) Gitter
? Bot adapter: (campfire)
>> Can't that adapter on NPM, try again?
```
Small grammar change.
> Update grammar in generators/app/index.js

- generators/app/templates/README.md
```
$ xargs -i
xargs: illegal option -- i
```
According to [this](http://stackoverflow.com/questions/5192564/sutble-difference-in-using-xargs-and-xargs-i):
> Also, `-i` for `xargs` was deprecated around version 4.2.9. You should use `-I {}`.
> `xargs -i` was removed

- README.md
It was renamed to index.md in https://github.com/github/hubot/pull/882
> Fix link to hubot's README

- generators/app/index.js
This came up in https://github.com/hubot-scripts/hubot-youtube/pull/4 and https://github.com/hubot-scripts/hubot-youtube/issues/3 . It's currently broken, and once updated to the new API would require manual configuration.
We want the out of box hubot experience to work without much configuration, and this would be an extra step.
cc @stephenyeargin
> Remove hubot-youtube, since it requires an API key now

- CHANGELOG.md
* [app] don't include youtube by default since the API is deprecated, and the new API requires an API key https://github.com/github/generator-hubot/pull/43
* [app] fix copy when can't find something on npm https://github.com/github/generator-hubot/pull/39 cc @ericdorsey 
* [app] update README to fix deprecated xargs argument https://github.com/github/generator-hubot/pull/41 cc @bkeepers
> Prepare for 0.3.1

- generators/app/templates/README.md
> One-word change to link to Windows instructions correctly in README template

- generators/script/templates/src/template.coffee
I got this error:
hubot> [Thu Aug 20 2015 10:49:13 GMT+0800 (CST)] ERROR ReferenceError: res is not defined
at TextListener.callback (/Users/tyan/GITHUB/hubot-maid/src/maid.coffee:22:5, <js>:7:14)
at executeListener (/Users/tyan/DEMO/myhubot/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
at allDone (/Users/tyan/DEMO/myhubot/node_modules/hubot/src/middleware.coffee:40:37, <js>:29:16)
at /Users/tyan/DEMO/myhubot/node_modules/hubot/node_modules/async/lib/async.js:274:13
at Object.async.eachSeries (/Users/tyan/DEMO/myhubot/node_modules/hubot/node_modules/async/lib/async.js:142:20)
at Object.async.reduce (/Users/tyan/DEMO/myhubot/node_modules/hubot/node_modules/async/lib/async.js:268:15)
at /Users/tyan/DEMO/myhubot/node_modules/hubot/src/middleware.coffee:45:7, <js>:32:22
at …
> miss (res) ?

- generators/app/templates/README.md
Fixes a couple broken links in the README template.
This is happening because the reference-style links are using parenthesis when they should use square brackets ([Markdown documentation on that matter](http://daringfireball.net/projects/markdown/syntax#link)).
> Fix a couple links in the README template

- generators/app/index.js
This can fix issues #64.
It seems that first argument of `done()` expects error object, and second one expects return value.
> Fix #64 prompting error

- generators/app/index.js
1. Removed what seemed like an extraneous console.log statement.
2. Changed variable name from 'available' to 'unavailable', to match both the npm-name api, and what the generator-hubot code is actually doing. Only the name of the variable was off, and was causing confusion.
> cleaned up checking of availability of adapter on npm

- package.json
This corrects the error 
```
UNMET PEER DEPENDENCY yo@>=1.0.0
npm WARN EPEERINVALID generator-hubot@0.3.1 requires a peer of yo@>=1.0.0 but none was installed.
``` 
when using npm 3.3.11 and node 4.2.1.
> remove broken yo peer dependency

- generators/app/templates/bin/hubot.cmd
This fixes issues with coffee-script not being installed globally and potentially other binary conflicts.
> Set path to sync hubot.cmd with hubot bash script

- generators/script/templates/.travis.yml
Since version 0.10 does not have Promise, hubot-test-helper can not be used.
Travis CI log:
```console
...
$ npm test
...
1) foobar responds to hello:
ReferenceError: Promise is not defined
at Room.receive (node_modules/hubot-test-helper/lib/index.js:79:18)
at Object.Room.user.say (node_modules/hubot-test-helper/lib/index.js:62:26)
at Context.<anonymous> (test/foobar-test.coffee:21:29)
2) foobar hears orly:
ReferenceError: Promise is not defined
at Room.receive (node_modules/hubot-test-helper/lib/index.js:79:18)
at Object.Room.user.say (node_modules/hubot-test-helper/lib/index.js:62:26)
at Context.<anonymous> (test/foobar-test.coffee:27:29)
...
```
Remove version 0.10.
Add version the latest node and 6, 5, 4.
> Fix js version to test with Travis CI

- generators/app/index.js
- test/test-app.js
This file is no longer used; the generator creates an empty one and the
bot then produces a warning to delete the empty file.  This patch just
removes the file from the generator so fresh installs never need to care
about this.
closes #75
> Remove references to hubot-scripts.json fixes #75

- generators/app/index.js
Now that Hubot 3 is stable, this sets the generator to create a Hubot using the v3 packages. We should create a release with the `latest` tag once this is ready.
> feat(generators): use @latest tags

- .travis.yml
- generators/script/templates/.travis.yml
April 30, 2018 has come and gone, which means new versions of `node` for test coverage.
Reference: https://github.com/nodejs/Release
> Bumping the LTS versions for Travis CI

- package.json
I was wondering why things were being published under next 😅 This explains it.
> chore: publish to default tag, not next
